export const GET_ALL_CINEMA_LIST = "GET_ALL_CINEMA_LIST"

export const GET_CINEMA_DETAIL = "GET_CINEMA_DETAIL"

export const GET_CINEMA_DATA = "GET_CINEMA_DATA"

export const GET_CHOOSE_CARD_MSG = "GET_CHOOSE_CARD_MSG"








export const GET_ALL_MOVIE_LIST = "GET_ALL_MOVIE_LIST"

export const GET_ALL_CITY_LIST = "GET_ALL_CITY_LIST"
